version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
      - GOOS={{ .Os }}
      - GOARCH={{ .Arch }}
    goos:
      - freebsd
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - '386'
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: '386'
      - goos: windows
        goarch: '386'
    binary: '{{ .ProjectName }}'
    ldflags:
      - -s -w
      - -X github.com/sport24ru/terraform-provider-regru/version.Version={{ .Version }}
      - -X github.com/sport24ru/terraform-provider-regru/version.Commit={{ .Commit }}
      - -X github.com/sport24ru/terraform-provider-regru/version.Date={{ .Date }}

archives:
  - name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    formats: [ 'zip' ]

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256
  extra_files:
    - glob: "*.zip"

signs:
  - artifacts: checksum
    args:
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

# Terraform Registry Configuration
# Note: This will be handled by the release extra_files

release:
  draft: true
  prerelease: false
  # Include all documentation
  extra_files:
    - glob: README.md
    - glob: docs/**/*
    - glob: LICENSE
    - glob: terraform-registry-manifest.json
  # Release notes template
  name_template: 'v{{ .Version }}'
